# Generated by Django 2.0.5 on 2018-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
